use crate::parse::MacroInput;
use proc_macro2::{Literal, TokenStream};
use quote::quote;
use spec::{KalmanSpec, ModelSpec};

type Mat4 = nalgebra::Matrix4<f32>;
type Mat2 = nalgebra::Matrix2<f32>;
type Mat2x4 = nalgebra::Matrix2x4<f32>;
type Mat4x2 = nalgebra::Matrix4x2<f32>;

const MAX_ITER: usize = 1_000;
const CONV_TOL: f32 = 1e-9;
const BOUNDARY_EPS: f32 = 1e-6;

pub fn expand(input: &MacroInput) -> TokenStream {
    let path = resolve_spec_path(&input.spec_path);
    let spec = spec_loader::load(&path)
        .unwrap_or_else(|e| panic!("bayesian_filter!: failed to load {}: {}", path.display(), e));

    match spec {
        ModelSpec::Kalman(k) => expand_kalman(&input.name, &k),
        ModelSpec::GammaPoisson(_) => quote! {
            compile_error!("bayesian_filter!: GammaPoisson dispatch not yet implemented");
        },
        ModelSpec::EkfBearing(_) => quote! {
            compile_error!("bayesian_filter!: EkfBearing dispatch not yet implemented");
        },
    }
}

/// Resolve the spec path. Macro paths are relative to the invoking crate's
/// `Cargo.toml` directory; allow `MOONSHOT_MODEL` env var to override.
fn resolve_spec_path(p: &std::path::Path) -> std::path::PathBuf {
    if let Some(override_path) = std::env::var_os("MOONSHOT_MODEL") {
        return std::path::PathBuf::from(override_path);
    }
    if p.is_absolute() {
        return p.to_path_buf();
    }
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    manifest_dir.join(p)
}

fn expand_kalman(name: &syn::Ident, spec: &KalmanSpec) -> TokenStream {
    let f = mat4(&spec.f.0);
    let h = mat2x4(&spec.h.0);
    let q = mat4(&spec.q.0);
    let r = mat2(&spec.r.0);

    let (k_inf, _iters, spectral_radius) =
        cayley_riccati(&f, &h, &q, &r, &spec.state_scale, spec.cayley_alpha);

    // Emit each constant as a precise f32 literal.
    let f_lits = matrix_lits_4x4(&f);
    let h_lits = matrix_lits_2x4(&h);
    let k_lits = matrix_lits_4x2(&k_inf);
    let radius_lit = Literal::f32_unsuffixed(spectral_radius);

    quote! {
        /// Specialised Kalman filter generated by `bayesian_filter!`.
        ///
        /// `K_INF` (steady-state Kalman gain), `F` (state transition), and
        /// `H` (observation) are baked in as f32 literals at macro-expansion
        /// time. The `update` body is straight-line arithmetic with no
        /// allocations and no nalgebra dependency in the output.
        ///
        /// Closed-loop spectral radius (verified at compile time): #radius_lit.
        pub struct #name {
            pub x: [f32; 4],
        }

        impl #name {
            pub const fn new() -> Self {
                Self { x: [0.0; 4] }
            }

            #[allow(clippy::let_and_return)]
            pub fn update(&mut self, z_x: f32, z_y: f32) {
                const F: [[f32; 4]; 4] = #f_lits;
                const H: [[f32; 4]; 2] = #h_lits;
                const K: [[f32; 2]; 4] = #k_lits;
                const _CLOSED_LOOP_SPECTRAL_RADIUS: f32 = #radius_lit;

                // predict: x_pred = F · x
                let xp0 = F[0][0]*self.x[0] + F[0][1]*self.x[1] + F[0][2]*self.x[2] + F[0][3]*self.x[3];
                let xp1 = F[1][0]*self.x[0] + F[1][1]*self.x[1] + F[1][2]*self.x[2] + F[1][3]*self.x[3];
                let xp2 = F[2][0]*self.x[0] + F[2][1]*self.x[1] + F[2][2]*self.x[2] + F[2][3]*self.x[3];
                let xp3 = F[3][0]*self.x[0] + F[3][1]*self.x[1] + F[3][2]*self.x[2] + F[3][3]*self.x[3];

                // innovation: y = z − H · x_pred
                let in0 = z_x - (H[0][0]*xp0 + H[0][1]*xp1 + H[0][2]*xp2 + H[0][3]*xp3);
                let in1 = z_y - (H[1][0]*xp0 + H[1][1]*xp1 + H[1][2]*xp2 + H[1][3]*xp3);

                // update: x = x_pred + K · y
                self.x[0] = xp0 + K[0][0]*in0 + K[0][1]*in1;
                self.x[1] = xp1 + K[1][0]*in0 + K[1][1]*in1;
                self.x[2] = xp2 + K[2][0]*in0 + K[2][1]*in1;
                self.x[3] = xp3 + K[3][0]*in0 + K[3][1]*in1;
            }
        }
    }
}

fn cayley_riccati(
    f: &Mat4,
    h: &Mat2x4,
    q: &Mat4,
    r: &Mat2,
    state_scale: &[f32; 4],
    cayley_alpha: f32,
) -> (Mat4x2, usize, f32) {
    // State scaling.
    let d = Mat4::from_diagonal(&nalgebra::Vector4::new(
        state_scale[0], state_scale[1], state_scale[2], state_scale[3],
    ));
    let d_inv = d.try_inverse().expect("state_scale must be all non-zero");
    let f_s = d_inv * f * d;
    let q_s = d_inv * q * d_inv.transpose();
    let h_s = h * d;

    // Cayley iteration.
    let alpha_i = Mat4::identity() * cayley_alpha;
    let mut y = Mat4::zeros();
    let mut iters = 0;
    let mut p_inf = Mat4::identity() * cayley_alpha;

    for k in 0..MAX_ITER {
        let i_n = Mat4::identity();
        let one_minus_y_inv = (i_n - y).try_inverse().expect("(I − Y) singular");
        let p = (i_n + y) * one_minus_y_inv * cayley_alpha;
        let s = h_s * p * h_s.transpose() + r;
        let s_inv = s.try_inverse().expect("S singular");
        let p_new = f_s * p * f_s.transpose() + q_s
            - f_s * p * h_s.transpose() * s_inv * h_s * p * f_s.transpose();
        let p_plus = (p_new + alpha_i).try_inverse().expect("(P + αI) singular");
        let y_new = (p_new - alpha_i) * p_plus;

        let sigma_max = y_new.svd(false, false).singular_values[0];
        if 1.0 - sigma_max < BOUNDARY_EPS {
            panic!("bayesian_filter!: Cayley iterate at boundary at iter {}", k);
        }
        if (y_new - y).norm() < CONV_TOL {
            p_inf = p_new;
            iters = k + 1;
            break;
        }
        y = y_new;
        iters = k + 1;
        p_inf = p_new;
    }

    if iters == MAX_ITER {
        panic!("bayesian_filter!: Cayley-Riccati did not converge in {} iters", MAX_ITER);
    }

    // Recover K_inf in scaled coords, un-scale to physical.
    let s_inf = h_s * p_inf * h_s.transpose() + r;
    let k_inf_s = p_inf * h_s.transpose() * s_inf.try_inverse().expect("S_inf singular");
    let k_inf = d * k_inf_s;

    // Closed-loop stability check on the un-scaled system.
    let i_n = Mat4::identity();
    let f_cl = (i_n - k_inf * h) * f;
    let eigs = f_cl.complex_eigenvalues();
    let spectral_radius = eigs.iter().map(|e| e.norm()).fold(0.0_f32, f32::max);
    if !(spectral_radius < 1.0) {
        panic!(
            "bayesian_filter!: closed-loop unstable, spectral_radius = {} (must be < 1)",
            spectral_radius
        );
    }

    (k_inf, iters, spectral_radius)
}

fn mat4(rows: &[[f32; 4]; 4]) -> Mat4 {
    Mat4::from_row_slice(&rows.iter().flatten().copied().collect::<Vec<_>>())
}
fn mat2(rows: &[[f32; 2]; 2]) -> Mat2 {
    Mat2::from_row_slice(&rows.iter().flatten().copied().collect::<Vec<_>>())
}
fn mat2x4(rows: &[[f32; 4]; 2]) -> Mat2x4 {
    Mat2x4::from_row_slice(&rows.iter().flatten().copied().collect::<Vec<_>>())
}

fn matrix_lits_4x4(m: &Mat4) -> TokenStream {
    let rows: Vec<TokenStream> = (0..4)
        .map(|r| {
            let elems: Vec<Literal> =
                (0..4).map(|c| Literal::f32_unsuffixed(m[(r, c)])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}

fn matrix_lits_2x4(m: &Mat2x4) -> TokenStream {
    let rows: Vec<TokenStream> = (0..2)
        .map(|r| {
            let elems: Vec<Literal> =
                (0..4).map(|c| Literal::f32_unsuffixed(m[(r, c)])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}

fn matrix_lits_4x2(m: &Mat4x2) -> TokenStream {
    let rows: Vec<TokenStream> = (0..4)
        .map(|r| {
            let elems: Vec<Literal> =
                (0..2).map(|c| Literal::f32_unsuffixed(m[(r, c)])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}
