use crate::parse::MacroInput;
use proc_macro2::{Literal, TokenStream};
use quote::quote;
use spec::{KalmanSpec, ModelSpec};

pub fn expand(input: &MacroInput) -> TokenStream {
    let path = resolve_spec_path(&input.spec_path);
    let spec = spec_loader::load(&path)
        .unwrap_or_else(|e| panic!("bayesian_filter!: failed to load {}: {}", path.display(), e));

    match spec {
        ModelSpec::Kalman(k) => expand_kalman(&input.name, &k),
        ModelSpec::GammaPoisson(_) => quote! {
            compile_error!("bayesian_filter!: GammaPoisson dispatch not yet implemented");
        },
        ModelSpec::EkfBearing(_) => quote! {
            compile_error!("bayesian_filter!: EkfBearing dispatch not yet implemented");
        },
    }
}

/// Resolve the spec path. Macro paths are relative to the invoking crate's
/// `Cargo.toml` directory; allow `MOONSHOT_MODEL` env var to override.
fn resolve_spec_path(p: &std::path::Path) -> std::path::PathBuf {
    if let Some(override_path) = std::env::var_os("MOONSHOT_MODEL") {
        return std::path::PathBuf::from(override_path);
    }
    if p.is_absolute() {
        return p.to_path_buf();
    }
    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| std::path::PathBuf::from("."));
    manifest_dir.join(p)
}

fn expand_kalman(name: &syn::Ident, spec: &KalmanSpec) -> TokenStream {
    let solved = riccati::solve(spec)
        .unwrap_or_else(|e| panic!("bayesian_filter!: Riccati solve failed — {}", e));

    let f_lits = matrix_lits_4x4(&spec.f.0);
    let h_lits = matrix_lits_2x4(&spec.h.0);
    let k_lits = matrix_lits_4x2(&solved.k_inf);
    let radius_lit = Literal::f32_unsuffixed(solved.spectral_radius);

    quote! {
        /// Specialised Kalman filter generated by `bayesian_filter!`.
        ///
        /// `K_INF` (steady-state Kalman gain), `F` (state transition), and
        /// `H` (observation) are baked in as f32 literals at macro-expansion
        /// time. The `update` body is straight-line arithmetic with no
        /// allocations and no nalgebra dependency in the output.
        ///
        /// Closed-loop spectral radius (verified at compile time): #radius_lit.
        pub struct #name {
            pub x: [f32; 4],
        }

        impl #name {
            pub const fn new() -> Self {
                Self { x: [0.0; 4] }
            }

            #[allow(clippy::let_and_return)]
            pub fn update(&mut self, z_x: f32, z_y: f32) {
                const F: [[f32; 4]; 4] = #f_lits;
                const H: [[f32; 4]; 2] = #h_lits;
                const K: [[f32; 2]; 4] = #k_lits;
                const _CLOSED_LOOP_SPECTRAL_RADIUS: f32 = #radius_lit;

                // predict: x_pred = F · x
                let xp0 = F[0][0]*self.x[0] + F[0][1]*self.x[1] + F[0][2]*self.x[2] + F[0][3]*self.x[3];
                let xp1 = F[1][0]*self.x[0] + F[1][1]*self.x[1] + F[1][2]*self.x[2] + F[1][3]*self.x[3];
                let xp2 = F[2][0]*self.x[0] + F[2][1]*self.x[1] + F[2][2]*self.x[2] + F[2][3]*self.x[3];
                let xp3 = F[3][0]*self.x[0] + F[3][1]*self.x[1] + F[3][2]*self.x[2] + F[3][3]*self.x[3];

                // innovation: y = z − H · x_pred
                let in0 = z_x - (H[0][0]*xp0 + H[0][1]*xp1 + H[0][2]*xp2 + H[0][3]*xp3);
                let in1 = z_y - (H[1][0]*xp0 + H[1][1]*xp1 + H[1][2]*xp2 + H[1][3]*xp3);

                // update: x = x_pred + K · y
                self.x[0] = xp0 + K[0][0]*in0 + K[0][1]*in1;
                self.x[1] = xp1 + K[1][0]*in0 + K[1][1]*in1;
                self.x[2] = xp2 + K[2][0]*in0 + K[2][1]*in1;
                self.x[3] = xp3 + K[3][0]*in0 + K[3][1]*in1;
            }
        }
    }
}

fn matrix_lits_4x4(m: &[[f32; 4]; 4]) -> TokenStream {
    let rows: Vec<TokenStream> = (0..4)
        .map(|r| {
            let elems: Vec<Literal> = (0..4).map(|c| Literal::f32_unsuffixed(m[r][c])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}

fn matrix_lits_2x4(m: &[[f32; 4]; 2]) -> TokenStream {
    let rows: Vec<TokenStream> = (0..2)
        .map(|r| {
            let elems: Vec<Literal> = (0..4).map(|c| Literal::f32_unsuffixed(m[r][c])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}

fn matrix_lits_4x2(m: &[[f32; 2]; 4]) -> TokenStream {
    let rows: Vec<TokenStream> = (0..4)
        .map(|r| {
            let elems: Vec<Literal> = (0..2).map(|c| Literal::f32_unsuffixed(m[r][c])).collect();
            quote! { [#(#elems),*] }
        })
        .collect();
    quote! { [#(#rows),*] }
}
